import fs from "fs";
import path from "path";
import type { DB, Formation, Resource } from "./types";
import { hashPassword } from "./auth";

const DATA_DIR = path.join(process.cwd(), "data");
const FILE = path.join(DATA_DIR, "db.json");

let cache: DB | null = null;

const R = (
  id: string,
  title: string,
  subject: string,
  level: Resource["level"],
  type: Resource["type"],
  premium: boolean,
  description: string,
  preview: string,
  tags: string[]
): Resource => ({ id, title, subject, level, type, premium, description, preview, tags, createdAt: Date.now() });

const F = (id: string, title: string, level: string, description: string, preview: string): Formation =>
  ({ id, title, level, description, preview, createdAt: Date.now() });

function seed(): DB {
  const adminPw = hashPassword("Admin@2026");
  const demoPw = hashPassword("Demo@1234");
  const now = Date.now();
  return {
    users: [
      {
        id: "u-admin", name: "Administration RÉUSSIR POLYTECH", email: "admin@reussirpolytech.com", phone: "672356441",
        passHash: adminPw.hash, passSalt: adminPw.salt, level: "MSP2", role: "admin", createdAt: now, unlocked: [], study: [],
      },
      {
        id: "u-demo", name: "Étudiant Démo", email: "etudiant@demo.rp", phone: "699000000",
        passHash: demoPw.hash, passSalt: demoPw.salt, level: "MSP1", role: "student", createdAt: now,
        unlocked: ["m1-ar1-cor"],
        study: [
          { id: "s-1", subject: "math", topic: "Refaire la fiche TD 1 d'Analyse réelle 1", done: true },
          { id: "s-2", subject: "physique", topic: "Épreuve blanche de Mécanique du point chronométrée", done: false },
        ],
      },
    ],
    resources: [
      /* ========== MSP1 · S1 ========== */
      R("m1-ar1-td", "Fiches de TD — Analyse réelle 1", "analyse-reelle-1", "MSP1", "td", false,
        "L'ensemble des fiches de TD d'Analyse réelle 1 (semestre 1) : énoncés progressifs conformes au programme officiel.",
        "TD 1 — Suites numériques\nEx. 1 : Étudier la limite de u_n = (n²+1)/(2n²−3).\nEx. 2 : Montrer que u_{n+1} = sqrt(2+u_n) converge.",
        ["td", "analyse"]),
      R("m1-ar1-ex", "Épreuves / Examens — Analyse réelle 1", "analyse-reelle-1", "MSP1", "examens", false,
        "Les épreuves d'Analyse réelle 1 des sessions récentes, telles que distribuées en évaluation.",
        "Session 2025 — Problème 1 (8 points)\nÉtude de la suite u_{n+1} = (u_n² + 2)/(2u_n).",
        ["examens", "annales"]),
      R("m1-ar1-cor", "Corrections détaillées — Analyse réelle 1", "analyse-reelle-1", "MSP1", "corrections", true,
        "Corrections rédigées pas à pas de toutes les fiches de TD et épreuves d'Analyse réelle 1, avec barèmes et conseils de rédaction.",
        "Corrigé TD 1 Ex. 2 — u_{n+1} = sqrt(2+u_n) croissante et majorée par 2 donc convergente ; l = 2.",
        ["corrections", "protégé"]),
      R("m1-ag-td", "Fiches de TD — Algèbre Générale", "algebre-generale", "MSP1", "td", false,
        "Fiches de TD d'Algèbre Générale : groupes, anneaux, corps et arithmétique, avec exercices types.",
        "TD 2 — Groupes\nEx. 3 : Montrer que (ℤ/n, +) est cyclique.",
        ["td", "algèbre"]),
      R("m1-ag-cor", "Corrections détaillées — Algèbre Générale", "algebre-generale", "MSP1", "corrections", true,
        "Corrections complètes des fiches de TD d'Algèbre Générale, rédigées par le collectif.",
        "Corrigé TD 2 Ex. 3 — 1̄ engendre /nℤ : tout élément est multiple de 1̄.",
        ["corrections", "protégé"]),
      R("m1-em1-td", "Fiches de TD — Électromagnétisme 1", "electromagnetisme-1", "MSP1", "td", false,
        "Fiches de TD d'Électromagnétisme 1 : applications de Gauss et d'Ampère, calculs de champs.",
        "TD 1 — Théorème de Gauss\nEx. 2 : Champ d'un plan infini uniformément chargé.",
        ["td", "électromagnétisme"]),
      R("m1-em1-ex", "Épreuves / Examens — Électromagnétisme 1", "electromagnetisme-1", "MSP1", "examens", false,
        "Épreuves d'Électromagnétisme 1 des sessions récentes.",
        "Session 2025 — Exercice 3 (5 points) : champ créé par un fil infini.",
        ["examens", "annales"]),
      R("m1-em1-cor", "Corrections détaillées — Électromagnétisme 1", "electromagnetisme-1", "MSP1", "corrections", true,
        "Corrections rédigées des TD et épreuves d'Électromagnétisme 1, avec schémas bilan.",
        "Corrigé ex. 3 — Ampère : B = μ₀I/(2πr), lignes de champ circulaires.",
        ["corrections", "protégé"]),
      R("m1-mp-td", "Fiches de TD — Mécanique du point", "mecanique-point", "MSP1", "td", false,
        "Fiches de TD de Mécanique du point : cinématique, dynamique, énergie.",
        "TD 3 — Projectile avec frottement fluide linéaire.",
        ["td", "mécanique"]),
      R("m1-mp-ex", "Épreuves / Examens — Mécanique du point", "mecanique-point", "MSP1", "examens", false,
        "Épreuves de Mécanique du point des sessions récentes.",
        "Session 2025 — Problème 2 : pendule simple amorti.",
        ["examens", "annales"]),
      R("m1-mp-cor", "Corrections détaillées — Mécanique du point", "mecanique-point", "MSP1", "corrections", true,
        "Corrections complètes des TD et épreuves de Mécanique du point, avec schémas bilan soignés.",
        "Corrigé problème 2 — θ'' + 2λθ' + ω₀²θ = 0 : régime pseudo-périodique si λ < ω₀.",
        ["corrections", "protégé"]),
      R("m1-inf1-td", "Fiches de TD — Informatique 1", "informatique-1", "MSP1", "td", false,
        "Fiches de TD d'Informatique 1 : algorithmique, complexité et programmation C.",
        "TD 4 — Récursivité : tours de Hanoï et complexité.",
        ["td", "informatique"]),
      R("m1-inf1-ex", "Épreuves / Examens — Informatique 1", "informatique-1", "MSP1", "examens", false,
        "Épreuves d'Informatique 1 : traces d'algorithmes et écriture de fonctions C.",
        "Session 2025 — Exercice 1 : trace de mystere(5).",
        ["examens", "annales"]),
      R("m1-inf1-cor", "Corrections détaillées — Informatique 1", "informatique-1", "MSP1", "corrections", true,
        "Corrections commentées des TD et épreuves d'Informatique 1, avec code de référence.",
        "Corrigé ex. 1 — mystere(5) = 120 (factorielle récursive).",
        ["corrections", "protégé"]),
      R("m1-chim-td", "Fiches de TD — Éléments de Chimie", "elements-chimie", "MSP1", "td", false,
        "Fiches de TD d'Éléments de Chimie : atome, liaison, solutions et pH.",
        "TD 2 — Concentrations et dilutions.",
        ["td", "chimie"]),
      R("m1-tp-td", "Fiches de TP — TP Physique", "tp-physique", "MSP1", "td", false,
        "Protocoles et fiches de TP Physique du semestre 1, avec modèles de comptes-rendus.",
        "TP 2 — Pendule simple : mesure de g et incertitudes.",
        ["tp", "physique"]),

      /* ========== MSP1 · S2 ========== */
      R("m1-ar2-td", "Fiches de TD — Analyse réelle 2", "analyse-reelle-2", "MSP1", "td", false,
        "Fiches de TD d'Analyse réelle 2 : séries numériques et séries de fonctions.",
        "TD 1 — Nature de Σ 1/(n ln n).",
        ["td", "analyse"]),
      R("m1-ar2-ex", "Épreuves / Examens — Analyse réelle 2", "analyse-reelle-2", "MSP1", "examens", false,
        "Épreuves d'Analyse réelle 2 des sessions récentes.",
        "Session 2026 — Exercice 3 : rayon de convergence de Σ (n²/3ⁿ) xⁿ.",
        ["examens", "annales"]),
      R("m1-ar2-cor", "Corrections détaillées — Analyse réelle 2", "analyse-reelle-2", "MSP1", "corrections", true,
        "Corrections rédigées des TD et épreuves d'Analyse réelle 2.",
        "Corrigé ex. 3 — d'Alembert : R = 3.",
        ["corrections", "protégé"]),
      R("m1-al-td", "Fiches de TD — Algèbre linéaire", "algebre-lineaire", "MSP1", "td", false,
        "Fiches de TD d'Algèbre linéaire : matrices, déterminants, réduction.",
        "TD 3 — Diagonalisation de matrices 3×3.",
        ["td", "algèbre"]),
      R("m1-al-cor", "Corrections détaillées — Algèbre linéaire", "algebre-lineaire", "MSP1", "corrections", true,
        "Corrections complètes des TD d'Algèbre linéaire.",
        "Corrigé TD 3 — polynôme caractéristique et sous-espaces propres.",
        ["corrections", "protégé"]),
      R("m1-em2-td", "Fiches de TD — Électromagnétisme 2", "electromagnetisme-2", "MSP1", "td", false,
        "Fiches de TD d'Électromagnétisme 2 : Maxwell et propagation.",
        "TD 2 — Équation de propagation dans le vide.",
        ["td", "maxwell"]),
      R("m1-geo-td", "Fiches de TD — Géométrie euclidienne et affine", "geometrie", "MSP1", "td", false,
        "Fiches de TD de Géométrie : espaces affines, isométries, produits scalaires.",
        "TD 1 — Repères affines et barycentres.",
        ["td", "géométrie"]),
      R("m1-inf2-td", "Fiches de TD — Informatique 2", "informatique-2", "MSP1", "td", false,
        "Fiches de TD d'Informatique 2 : C++, classes et héritage.",
        "TD 2 — Concevoir une hiérarchie de classes Forme/Cercle/Rectangle.",
        ["td", "C++"]),
      R("m1-inf2-ex", "Épreuves / Examens — Informatique 2", "informatique-2", "MSP1", "examens", false,
        "Épreuves d'Informatique 2 des sessions récentes.",
        "Session 2026 — Problème 1 : UML → C++.",
        ["examens", "annales"]),
      R("m1-inf2-cor", "Corrections détaillées — Informatique 2", "informatique-2", "MSP1", "corrections", true,
        "Corrections commentées des TD et épreuves d'Informatique 2.",
        "Corrigé problème 1 — classe abstraite Forme et polymorphisme.",
        ["corrections", "protégé"]),

      /* ========== MSP2 · S1 ========== */
      R("m2-am-td", "Fiches de TD — Algèbre multilinéaire", "algebre-multilineaire", "MSP2", "td", false,
        "Fiches de TD d'Algèbre multilinéaire : formes linéaires, formes quadratiques, tenseurs.",
        "TD 2 — Signature d'une forme quadratique.",
        ["td", "algèbre"]),
      R("m2-am-cor", "Corrections détaillées — Algèbre multilinéaire", "algebre-multilineaire", "MSP2", "corrections", true,
        "Corrections rédigées des TD d'Algèbre multilinéaire.",
        "Corrigé TD 2 — réduction de Gauss et signature (2,1).",
        ["corrections", "protégé"]),
      R("m2-si-td", "Fiches de TD — Séries intégrales", "series-integrales", "MSP2", "td", false,
        "Fiches de TD de Séries intégrales : intégrales impropres, convergence, comparaison.",
        "TD 1 — Nature de ∫₀^∞ sin(x)/x dx.",
        ["td", "analyse"]),
      R("m2-si-ex", "Épreuves / Examens — Séries intégrales", "series-integrales", "MSP2", "examens", false,
        "Épreuves de Séries intégrales des sessions récentes.",
        "Session 2026 — Problème 1 : intégrales de Bertrand.",
        ["examens", "annales"]),
      R("m2-si-cor", "Corrections détaillées — Séries intégrales", "series-integrales", "MSP2", "corrections", true,
        "Corrections complètes des TD et épreuves de Séries intégrales.",
        "Corrigé problème 1 — convergence ssi α > 1.",
        ["corrections", "protégé"]),
      R("m2-ps-td", "Fiches de TD — Probabilités et statistiques", "probabilites-stats", "MSP2", "td", false,
        "Fiches de TD de Probabilités et statistiques : lois, espérance, estimation.",
        "TD 3 — Estimateur du maximum de vraisemblance.",
        ["td", "probabilités"]),
      R("m2-ps-ex", "Épreuves / Examens — Probabilités et statistiques", "probabilites-stats", "MSP2", "examens", false,
        "Épreuves de Probabilités et statistiques des sessions récentes.",
        "Session 2026 — Exercice 4 : TCL et intervalle de confiance.",
        ["examens", "annales"]),
      R("m2-ps-cor", "Corrections détaillées — Probabilités et statistiques", "probabilites-stats", "MSP2", "corrections", true,
        "Corrections rédigées des TD et épreuves de Probabilités et statistiques.",
        "Corrigé ex. 4 — IC à 95 % : [x̄ − 1,96σ/√n ; x̄ + 1,96σ/√n].",
        ["corrections", "protégé"]),
      R("m2-ms-td", "Fiches de TD — Mécanique des solides", "mecanique-solides", "MSP2", "td", false,
        "Fiches de TD de Mécanique des solides : torseurs, cinématique du solide.",
        "TD 1 — Torseur cinétique d'une barre en rotation.",
        ["td", "mécanique"]),
      R("m2-ec-td", "Fiches de TD — Électrocinétique", "electrocinetique", "MSP2", "td", false,
        "Fiches de TD d'Électrocinétique : circuits RC, RL, RLC en régimes transitoire et sinusoïdal.",
        "TD 2 — Réponse d'un circuit RC à un échelon.",
        ["td", "circuits"]),
      R("m2-ec-ex", "Épreuves / Examens — Électrocinétique", "electrocinetique", "MSP2", "examens", false,
        "Épreuves d'Électrocinétique des sessions récentes.",
        "Session 2026 — Problème 2 : filtre passe-bande RLC.",
        ["examens", "annales"]),
      R("m2-ec-cor", "Corrections détaillées — Électrocinétique", "electrocinetique", "MSP2", "corrections", true,
        "Corrections complètes des TD et épreuves d'Électrocinétique.",
        "Corrigé problème 2 — fonction de transfert et facteur de qualité.",
        ["corrections", "protégé"]),
      R("m2-inf3-td", "Fiches de TD — Informatique 3", "informatique-3", "MSP2", "td", false,
        "Fiches de TD d'Informatique 3 : structures de données avancées, STL et complexité.",
        "TD 2 — Arbres binaires de recherche et équilibrage.",
        ["td", "C++"]),
      R("m2-inf3-ex", "Épreuves / Examens — Informatique 3", "informatique-3", "MSP2", "examens", false,
        "Épreuves d'Informatique 3 des sessions récentes.",
        "Session 2026 — Exercice 3 : complexité d'un tri par tas.",
        ["examens", "annales"]),
      R("m2-tp-td", "Fiches de TP — TP Physique (MSP2)", "tp-physique-m2", "MSP2", "td", false,
        "Protocoles de TP Physique de niveau 2, avec modèles de comptes-rendus.",
        "TP 1 — Circuit RLC : résonance et bande passante.",
        ["tp", "physique"]),

      /* ========== MSP2 · S2 ========== */
      R("m2-aev-td", "Fiches de TD — Analyse dans les espaces vectoriels de dimensions finies", "analyse-espaces-dim-finies", "MSP2", "td", false,
        "Fiches de TD : normes, topologie, applications linéaires continues en dimension finie.",
        "TD 1 — Normes équivalentes sur ℝⁿ.",
        ["td", "analyse"]),
      R("m2-aev-cor", "Corrections détaillées — Analyse dans les EV de dimensions finies", "analyse-espaces-dim-finies", "MSP2", "corrections", true,
        "Corrections rédigées des TD d'analyse en dimension finie.",
        "Corrigé TD 1 — toute norme sur ℝⁿ est équivalente à la norme ‖·‖∞.",
        ["corrections", "protégé"]),
      R("m2-an-td", "Fiches de TD — Analyse numérique", "analyse-numerique", "MSP2", "td", false,
        "Fiches de TD d'Analyse numérique : méthodes de Newton, interpolation, intégration numérique.",
        "TD 2 — Méthode de Newton : convergence quadratique.",
        ["td", "numérique"]),
      R("m2-an-ex", "Épreuves / Examens — Analyse numérique", "analyse-numerique", "MSP2", "examens", false,
        "Épreuves d'Analyse numérique des sessions récentes.",
        "Session 2026 — Problème 1 : interpolation de Lagrange.",
        ["examens", "annales"]),
      R("m2-ce-td", "Fiches de TD — Circuits électriques et électroniques", "circuits-electriques", "MSP2", "td", false,
        "Fiches de TD : analyse de circuits, amplificateurs opérationnels, diodes et transistors.",
        "TD 3 — Montage amplificateur inverseur : gain et bande passante.",
        ["td", "électronique"]),
      R("m2-ce-ex", "Épreuves / Examens — Circuits électriques et électroniques", "circuits-electriques", "MSP2", "examens", false,
        "Épreuves de Circuits électriques et électroniques des sessions récentes.",
        "Session 2026 — Problème 2 : redressement double alternance.",
        ["examens", "annales"]),
      R("m2-ce-cor", "Corrections détaillées — Circuits électriques et électroniques", "circuits-electriques", "MSP2", "corrections", true,
        "Corrections complètes des TD et épreuves de Circuits électriques et électroniques.",
        "Corrigé problème 2 — tension de sortie et taux d'ondulation.",
        ["corrections", "protégé"]),
      R("m2-og-td", "Fiches de TD — Optique géométrique et ondulatoire", "optique-geo-ondulatoire", "MSP2", "td", false,
        "Fiches de TD : lentilles, miroirs, interférences et diffraction.",
        "TD 2 — Fentes d'Young : interfrange et contraste.",
        ["td", "optique"]),
      R("m2-th-td", "Fiches de TD — Thermodynamique", "thermodynamique", "MSP2", "td", false,
        "Fiches de TD de Thermodynamique : principes, machines, diagrammes.",
        "TD 3 — Cycle de Carnot : rendement et bilans entropiques.",
        ["td", "thermo"]),
      R("m2-th-ex", "Épreuves / Examens — Thermodynamique", "thermodynamique", "MSP2", "examens", false,
        "Épreuves de Thermodynamique des sessions récentes.",
        "Session 2026 — Problème 1 : machine frigorifique et COP.",
        ["examens", "annales"]),
      R("m2-th-cor", "Corrections détaillées — Thermodynamique", "thermodynamique", "MSP2", "corrections", true,
        "Corrections rédigées des TD et épreuves de Thermodynamique.",
        "Corrigé problème 1 — COP = T_f/(T_c − T_f).",
        ["corrections", "protégé"]),
      R("m2-st-td", "Fiches de TD — Statique", "statique", "MSP2", "td", false,
        "Fiches de TD de Statique : équilibre des solides, torseurs, liaisons.",
        "TD 1 — Principe fondamental de la statique sur un portique.",
        ["td", "statique"]),
      R("m2-inf4-td", "Fiches de TD — Informatique 4", "informatique-4", "MSP2", "td", false,
        "Fiches de TD d'Informatique 4 : programmation avancée, motifs de conception et projets.",
        "TD 2 — Patrons observateur et stratégie en C++.",
        ["td", "C++"]),
      R("m2-inf4-ex", "Épreuves / Examens — Informatique 4", "informatique-4", "MSP2", "examens", false,
        "Épreuves d'Informatique 4 des sessions récentes.",
        "Session 2026 — Projet : mini-bibliothèque orientée objet.",
        ["examens", "annales"]),
      R("m2-inf4-cor", "Corrections détaillées — Informatique 4", "informatique-4", "MSP2", "corrections", true,
        "Corrections commentées des TD et épreuves d'Informatique 4.",
        "Corrigé projet — architecture en couches et tests unitaires.",
        ["corrections", "protégé"]),
    ],
    requests: [
      { id: "req-0001", userId: "u-demo", resourceId: "m1-ar1-cor", status: "approved", createdAt: now - 86400000 * 3, updatedAt: now - 86400000 * 2 },
      { id: "req-0002", userId: "u-demo", resourceId: "m1-ar2-cor", status: "pending", createdAt: now - 3600000 * 5, updatedAt: now - 3600000 * 5 },
    ],
    sessions: [],
    announcements: [
      { id: "a-1", title: "Séance de révision collective — Analyse réelle 1", date: "2026-09-12", body: "Samedi 14h, salle B12 : correction collective du TD 3 animée par les leaders de cadets. Ouvert à tous les MSP1." },
      { id: "a-2", title: "Nouvelles corrections MSP2 disponibles", date: "2026-09-02", body: "Les corrections détaillées de Séries intégrales, Électrocinétique et Thermodynamique (sessions 2026) sont en ligne : demandez l'accès via WhatsApp." },
      { id: "a-3", title: "Formations VIP — cohorte d'octobre", date: "2026-08-28", body: "Intelligence artificielle, leadership et gestion de projet : les inscriptions de la cohorte d'octobre sont ouvertes via WhatsApp." },
    ],
    formations: [
      F("vip-ia", "Intelligence artificielle", "Intermédiaire",
        "Comprendre et utiliser l'IA : fondamentaux du machine learning, prompt engineering professionnel et outils IA pour l'ingénieur.",
        "Module 1 — Panorama de l'IA moderne\nModule 2 — Prompt engineering pour les études et le travail\nModule 3 — Construire un premier modèle supervisé"),
      F("vip-prog", "Programmation", "Débutant à avancé",
        "Du C au C++ moderne et à Python : algorithmique robuste, structures de données et bonnes pratiques professionnelles.",
        "Module 1 — C avancé (pointeurs, mémoire)\nModule 2 — C++ moderne et STL\nModule 3 — Python pour l'ingénieur"),
      F("vip-info", "Informatique", "Débutant",
        "Culture numérique essentielle : système, réseaux, sécurité personnelle et outils de productivité de l'étudiant ingénieur.",
        "Module 1 — Système et fichiers\nModule 2 — Réseaux et sécurité de base\nModule 3 — Outils collaboratifs"),
      F("vip-bureautique", "Bureautique professionnelle", "Débutant",
        "Word, Excel, PowerPoint et rapports techniques : mettre en forme des documents d'ingénieur impeccables.",
        "Module 1 — Excel : formules et tableaux croisés\nModule 2 — Rapports Word normés\nModule 3 — Présentations qui convainquent"),
      F("vip-design", "Design intelligent", "Intermédiaire",
        "Design graphique orienté communication : identité visuelle, affiches professionnelles et contenu de marque.",
        "Module 1 — Fondamentaux de la composition\nModule 2 — Couleur et typographie\nModule 3 — Créer une identité de projet"),
      F("vip-leadership", "Leadership", "Tous niveaux",
        "Posture de leader : décision, responsabilité, motivation d'équipe et gestion des conflits, inspiré des certifications Coursera.",
        "Module 1 — Se leader soi-même\nModule 2 — Communiquer en leader\nModule 3 — Conduire une équipe projet"),
      F("vip-communication", "Communication", "Tous niveaux",
        "Prise de parole, écrits professionnels et communication digitale : faire valoir ses idées avec clarté.",
        "Module 1 — Structurer un message\nModule 2 — Parler en public\nModule 3 — Communication digitale"),
      F("vip-gestion", "Gestion de projet", "Intermédiaire",
        "Cadrage, planification, budget et risques : les méthodes des chefs de projet appliquées aux projets étudiants.",
        "Module 1 — Cadrer et planifier\nModule 2 — Suivre et piloter\nModule 3 — Clôturer et capitaliser"),
    ],
  };
}

export function getDB(): DB {
  if (cache) return cache;
  if (fs.existsSync(FILE)) {
    const parsed = JSON.parse(fs.readFileSync(FILE, "utf8")) as DB;
    if (!parsed.formations) parsed.formations = seed().formations;
    cache = parsed;
  } else {
    cache = seed();
    save();
  }
  return cache;
}

export function save(): void {
  if (!cache) return;
  fs.mkdirSync(DATA_DIR, { recursive: true });
  const tmp = FILE + ".tmp";
  fs.writeFileSync(tmp, JSON.stringify(cache, null, 2));
  fs.renameSync(tmp, FILE);
}

export const uid = (prefix: string) =>
  `${prefix}-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`;
